[package]
name = "test-app"
version = "0.1.0"
authors = ["Mathieu Poumeyrol <kali@zoy.org>"]
edition = "2018"
workspace = "../"

[features]
my-feature = []

[dev-dependencies]
dinghy-test = { path = "../../dinghy-test" }
